apiVersion: v1
kind: Service
metadata:
  namespace: keda
  creationTimestamp: null
  labels:
    app: activemq-service
  name: activemq-service
spec:
  ports:
  - name: 61616-80
    port: 80
    protocol: TCP
    targetPort: 61616
  selector:
    app: activemq
  type: ClusterIP
status:
  loadBalancer: {}
