apiVersion: v1
kind: Service
metadata:
  namespace: keda
  creationTimestamp: null
  labels:
    app: activemq-management-service-out
  name: activemq-management-service-out
spec:
  ports:
    - name: 8161-81
      nodePort: 31080
      port: 82
      protocol: TCP
      targetPort: 8161
  selector:
    app: activemq
  type: NodePort
status:
  loadBalancer: {}
